export interface Job {
  id: string;
  department: string;
  title: string;
  team?: string;
  category?: string;
  deadline?: string;
  expiredInfo?: string;
  location?: string;
  jobType?: string;
  education?: string;
  salaryType?: string;
  seniority?: string;
  experienceLevel?: string;
  skills?: string[];
  workAddress?: string;
  jobDescription?: string;
  description?: string;
  flex?: string[];
  icon?: string;
}

export const jobs: Job[] = [
  // 50% Engineering (12 jobs)
  {
    id: 'senior-software-engineer-1',
    department: 'Engineering',
    title: 'Senior Software Engineer (Frontend)',
    description: 'Build performant frontend applications with modern tooling.',
    jobDescription: 'Implement UI components, optimize rendering, and own frontend reliability.',
    location: 'Remote / Addis Ababa',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Senior',
    experienceLevel: '5+ years',
    skills: ['React', 'TypeScript', 'Accessibility'],
    workAddress: 'Remote',
    flex: ['Full-time', 'Hybrid'],
    icon: 'code',
  },
  {
    id: 'senior-software-engineer-2',
    department: 'Engineering',
    title: 'Senior Software Engineer (Backend)',
    description: 'Design and implement scalable backend services.',
    jobDescription: 'Build APIs, design data models, and improve system throughput.',
    location: 'Remote / Hybrid',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Senior',
    experienceLevel: '5+ years',
    skills: ['Node.js', 'Databases', 'Distributed Systems'],
    workAddress: 'Remote',
    flex: ['Full-time'],
    icon: 'storage',
  },
  {
    id: 'full-stack-developer-1',
    department: 'Engineering',
    title: 'Full-Stack Developer',
    description: 'Deliver end-to-end features across web stack.',
    jobDescription: 'Ship features from database schema to user-facing UI.',
    location: 'Addis Ababa / Remote',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Mid-Senior',
    experienceLevel: '3+ years',
    skills: ['Full-stack', 'React', 'Node.js'],
    workAddress: 'Addis Ababa',
    flex: ['Full-time', 'Hybrid'],
    icon: 'devices',
  },
  {
    id: 'platform-engineer-1',
    department: 'Engineering',
    title: 'Platform Engineer',
    description: 'Build and maintain platform tooling and CI/CD.',
    jobDescription: 'Automate deployments, improve runbooks, and enable developer productivity.',
    location: 'Remote',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Mid-Senior',
    experienceLevel: '3+ years',
    skills: ['Kubernetes', 'CI/CD', 'Terraform'],
    workAddress: 'Remote',
    flex: ['Full-time', 'Remote'],
    icon: 'cloud_queue',
  },
  {
    id: 'devops-engineer-1',
    department: 'Engineering',
    title: 'DevOps Engineer',
    description: 'Manage infrastructure and observability.',
    jobDescription: 'Ensure reliability, monitoring, and efficient incident response.',
    location: 'Addis Ababa / Remote',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Mid-Senior',
    experienceLevel: '3+ years',
    skills: ['AWS', 'Monitoring', 'Scripting'],
    workAddress: 'Addis Ababa',
    flex: ['Full-time'],
    icon: 'backup',
  },
  {
    id: 'sre-engineer-1',
    department: 'Engineering',
    title: 'Site Reliability Engineer',
    description: 'Drive reliability and scalability initiatives.',
    jobDescription: 'Work on SLIs, SLOs, and production systems.',
    location: 'Remote',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Senior',
    experienceLevel: '5+ years',
    skills: ['SRE', 'Observability', 'Incident Response'],
    workAddress: 'Remote',
    flex: ['Full-time'],
    icon: 'settings',
  },
  {
    id: 'qa-automation-engineer-1',
    department: 'Engineering',
    title: 'QA Automation Engineer',
    description: 'Build test automation and quality tooling.',
    jobDescription: 'Create robust test suites and CI integrations.',
    location: 'Addis Ababa',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Mid',
    experienceLevel: '2+ years',
    skills: ['Test Automation', 'Selenium', 'CI'],
    workAddress: 'Addis Ababa',
    flex: ['Full-time', 'Contract'],
    icon: 'bug_report',
  },
  {
    id: 'security-engineer-1',
    department: 'Engineering',
    title: 'Security Engineer',
    description: 'Protect systems with proactive security engineering.',
    jobDescription: 'Implement security controls and run threat assessments.',
    location: 'Remote',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Senior',
    experienceLevel: '4+ years',
    skills: ['Security', 'Penetration Testing', 'Hardening'],
    workAddress: 'Remote',
    flex: ['Full-time'],
    icon: 'security',
  },
  {
    id: 'data-engineer-1',
    department: 'Engineering',
    title: 'Data Engineer',
    description: 'Design reliable data pipelines.',
    jobDescription: 'Ingest, transform, and serve data for analytics and ML.',
    location: 'Addis Ababa / Remote',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Mid-Senior',
    experienceLevel: '3+ years',
    skills: ['ETL', 'Data Warehousing', 'Spark'],
    workAddress: 'Addis Ababa',
    flex: ['Full-time', 'Hybrid'],
    icon: 'insights',
  },
  {
    id: 'ml-engineer-1',
    department: 'Engineering',
    title: 'Machine Learning Engineer',
    description: 'Productionize ML models and pipelines.',
    jobDescription: 'Deploy models, monitor performance, and optimize inference.',
    location: 'Remote',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Master\'s or Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Mid-Senior',
    experienceLevel: '3+ years',
    skills: ['Python', 'Model Serving', 'MLOps'],
    workAddress: 'Remote',
    flex: ['Full-time'],
    icon: 'memory',
  },
  {
    id: 'solutions-architect-1',
    department: 'Engineering',
    title: 'Solutions Architect',
    description: 'Design technical solutions for enterprise customers.',
    jobDescription: 'Lead architecture design and implementation guidance.',
    location: 'Hybrid',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Senior',
    experienceLevel: '5+ years',
    skills: ['Architecture', 'Cloud', 'Integration'],
    workAddress: 'Hybrid',
    flex: ['Full-time'],
    icon: 'engineering',
  },
  {
    id: 'backend-engineer-2',
    department: 'Engineering',
    title: 'Backend Engineer',
    description: 'Develop microservices and backend APIs.',
    jobDescription: 'Collaborate on system design, performance, and scalability.',
    location: 'Remote / Addis Ababa',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Mid-Senior',
    experienceLevel: '3+ years',
    skills: ['Microservices', 'APIs', 'Databases'],
    workAddress: 'Remote',
    flex: ['Full-time', 'Hybrid'],
    icon: 'http',
  },
  // Remaining departments (2 jobs each = 12 jobs total)
  // Product Management
  {
    id: 'product-manager-1',
    department: 'Product Management',
    title: 'Product Manager',
    description: 'Define product strategy and roadmap.',
    jobDescription: 'Collaborate with engineering and design to ship high-impact features.',
    flex: ['Full-time'],
    icon: 'assignment',
  },
  {
    id: 'technical-product-lead-1',
    department: 'Product Management',
    title: 'Technical Product Lead',
    description: 'Bridge engineering and product strategy.',
    jobDescription: 'Drive product execution and technical requirements.',
    flex: ['Full-time'],
    icon: 'hub',
  },
  // Sales / Business Development
  {
    id: 'sales-executive-1',
    department: 'Sales / Business Development',
    title: 'Sales Executive',
    description: 'Drive new business opportunities and demos.',
    jobDescription: 'Prospect, demo, and close enterprise deals.',
    flex: ['Full-time'],
    icon: 'sales',
  },
  {
    id: 'business-dev-manager-1',
    department: 'Sales / Business Development',
    title: 'Business Development Manager',
    description: 'Develop strategic partnerships and channels.',
    jobDescription: 'Identify partnership opportunities and enable growth.',
    flex: ['Full-time'],
    icon: 'handshake',
  },
  // Marketing
  {
    id: 'marketing-specialist-1',
    department: 'Marketing',
    title: 'Marketing Specialist',
    description: 'Execute demand-gen campaigns and content.',
    jobDescription: 'Coordinate campaigns, track KPIs, and produce content.',
    flex: ['Full-time', 'Hybrid'],
    icon: 'campaign',
  },
  {
    id: 'content-strategist-1',
    department: 'Marketing',
    title: 'Content Strategist',
    description: 'Develop content plans and messaging.',
    jobDescription: 'Create content that supports product adoption and thought leadership.',
    flex: ['Contract'],
    icon: 'article',
  },
  // Human Resources
  {
    id: 'hr-generalist-1',
    department: 'Human Resources',
    title: 'HR Generalist',
    description: 'Support HR operations and employee relations.',
    jobDescription: 'Help implement HR programs and policies.',
    flex: ['Full-time'],
    icon: 'people',
  },
  {
    id: 'talent-acquisition-1',
    department: 'Human Resources',
    title: 'Talent Acquisition Specialist',
    description: 'Source and screen candidates for open roles.',
    jobDescription: 'Manage full-cycle recruitment for diverse teams.',
    flex: ['Full-time'],
    icon: 'search',
  },
  // Finance
  {
    id: 'financial-analyst-1',
    department: 'Finance',
    title: 'Financial Analyst',
    description: 'Perform financial planning and analysis.',
    jobDescription: 'Support budgeting, forecasting, and financial reporting.',
    flex: ['Full-time'],
    icon: 'insights',
  },
  {
    id: 'payroll-manager-1',
    department: 'Finance',
    title: 'Payroll Manager',
    description: 'Manage payroll and benefits administration.',
    jobDescription: 'Ensure timely and accurate payroll processing.',
    flex: ['Full-time'],
    icon: 'payment',
  },
  // Product Design
  {
    id: 'senior-product-designer-1',
    department: 'Product Design',
    title: 'Senior Product Designer',
    description: 'Lead product design and design systems.',
    jobDescription: 'Create design patterns and partner with product and engineering.',
    flex: ['Full-time'],
    icon: 'palette',
  },
  {
    id: 'ux-researcher-1',
    department: 'Product Design',
    title: 'UX Researcher',
    description: 'Conduct research to inform product decisions.',
    jobDescription: 'Run studies, analyze findings, and recommend improvements.',
    location: 'Remote / Hybrid',
    jobType: 'Full-time',
    deadline: 'Open',
    education: 'Bachelor\'s Degree',
    salaryType: 'Negotiable',
    seniority: 'Mid',
    experienceLevel: '2+ years',
    skills: ['User Research', 'Interviews', 'Usability Testing'],
    workAddress: 'Remote',
    flex: ['Full-time', 'Contract'],
    icon: 'insight',
  },
];

export default jobs;
